version: '3.1'
services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - APP_PORT=5000
      - CONFIG=dev
      - MONGODB_URI=mongodb://mongo:27017/sabroso_dev_test
    links: 
      - mongo
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - '27017:27017'
    volumes: 
      - ./data:/data/db